import type { Metadata } from "next"
import { InventoryClient } from "./InventoryClient"
import type { Product } from "./InventoryClient"

export const metadata: Metadata = { title: "Inventory" }

const MOCK_PRODUCTS: Product[] = [
  {
    id: "PRD-001",
    name: "Clover Station Duo",
    sku: "CLV-STA-DUO",
    brand: "Clover",
    category: "POS Systems",
    status: "Active",
    description: "Full-featured POS system with customer-facing display, 8\" merchant screen, receipt printer, and cash drawer support.",
    tags: ["pos", "clover", "dual-screen", "receipt-printer"],
    variants: [
      {
        id: "VAR-001-1",
        name: "Standard",
        sku: "CLV-STA-DUO-STD",
        cost: 499,
        price: 749,
        stock: 0,
        units: [
          { id: "U-001", serial: "CLV2024001234", status: "Available", notes: "" },
          { id: "U-002", serial: "CLV2024001235", status: "Available", notes: "" },
          { id: "U-003", serial: "CLV2024001236", status: "Deployed",  notes: "Jerusalem Sweets — deployed May 2026" },
          { id: "U-004", serial: "CLV2024001237", status: "Deployed",  notes: "Brooklyn Bistro — deployed Mar 2026" },
          { id: "U-005", serial: "CLV2024001238", status: "Reserved",  notes: "Hold for Upper West Cafe onboarding" },
        ],
      },
      {
        id: "VAR-001-2",
        name: "With Cash Drawer",
        sku: "CLV-STA-DUO-CD",
        cost: 549,
        price: 849,
        stock: 0,
        units: [
          { id: "U-006", serial: "CLV2024002001", status: "Available", notes: "" },
          { id: "U-007", serial: "CLV2024002002", status: "Deployed",  notes: "Maple Leaf Market" },
        ],
      },
    ],
  },
  {
    id: "PRD-002",
    name: "PAX A920 Pro",
    sku: "PAX-A920-PRO",
    brand: "PAX",
    category: "Terminals",
    status: "Active",
    description: "Android-based smart terminal with 5\" touchscreen, built-in printer, WiFi/4G/Bluetooth connectivity.",
    tags: ["android", "smart-terminal", "portable", "wifi", "4g"],
    variants: [
      {
        id: "VAR-002-1",
        name: "WiFi Only",
        sku: "PAX-A920-PRO-W",
        cost: 220,
        price: 349,
        stock: 0,
        units: [
          { id: "U-010", serial: "PAXA9200001", status: "Available", notes: "" },
          { id: "U-011", serial: "PAXA9200002", status: "Available", notes: "" },
          { id: "U-012", serial: "PAXA9200003", status: "Available", notes: "" },
          { id: "U-013", serial: "PAXA9200004", status: "Deployed",  notes: "Metro Gas Station" },
          { id: "U-014", serial: "PAXA9200005", status: "Defective", notes: "Screen cracked — RMA pending" },
        ],
      },
      {
        id: "VAR-002-2",
        name: "WiFi + 4G",
        sku: "PAX-A920-PRO-WC",
        cost: 265,
        price: 399,
        stock: 0,
        units: [
          { id: "U-015", serial: "PAXA9200101", status: "Available", notes: "" },
          { id: "U-016", serial: "PAXA9200102", status: "Deployed",  notes: "QuickStop Mart — roaming enabled" },
          { id: "U-017", serial: "PAXA9200103", status: "Reserved",  notes: "Pending Atlas Auto Parts install" },
        ],
      },
    ],
  },
  {
    id: "PRD-003",
    name: "Ingenico Desk/3500",
    sku: "ING-DSK-3500",
    brand: "Ingenico",
    category: "Terminals",
    status: "Active",
    description: "Countertop payment terminal with color display, contactless NFC, chip, swipe, and PIN pad.",
    tags: ["countertop", "nfc", "emv", "pinpad", "contactless"],
    variants: [
      {
        id: "VAR-003-1",
        name: "Ethernet",
        sku: "ING-DSK-3500-ETH",
        cost: 145,
        price: 229,
        stock: 0,
        units: [
          { id: "U-020", serial: "ING35000001", status: "Available", notes: "" },
          { id: "U-021", serial: "ING35000002", status: "Available", notes: "" },
          { id: "U-022", serial: "ING35000003", status: "Deployed",  notes: "Midtown Pharmacy" },
          { id: "U-023", serial: "ING35000004", status: "Deployed",  notes: "Garden State Deli" },
        ],
      },
      {
        id: "VAR-003-2",
        name: "WiFi",
        sku: "ING-DSK-3500-WF",
        cost: 165,
        price: 259,
        stock: 0,
        units: [
          { id: "U-024", serial: "ING35000101", status: "Available", notes: "" },
          { id: "U-025", serial: "ING35000102", status: "Deployed",  notes: "Harbor View Sushi" },
        ],
      },
    ],
  },
  {
    id: "PRD-004",
    name: "Epson TM-T88VII",
    sku: "EPS-TM-T88VII",
    brand: "Epson",
    category: "Printer",
    status: "Active",
    description: "High-speed thermal receipt printer, 80mm paper, USB/Ethernet/WiFi interfaces, auto-cutter.",
    tags: ["thermal", "receipt", "80mm", "autocutter", "usb", "ethernet"],
    variants: [
      {
        id: "VAR-004-1",
        name: "USB + Ethernet",
        sku: "EPS-TM-T88VII-UE",
        cost: 189,
        price: 299,
        stock: 0,
        units: [
          { id: "U-030", serial: "EPST880001", status: "Available", notes: "" },
          { id: "U-031", serial: "EPST880002", status: "Available", notes: "" },
          { id: "U-032", serial: "EPST880003", status: "Deployed",  notes: "Fresh Farms Grocery — kitchen station" },
        ],
      },
      {
        id: "VAR-004-2",
        name: "USB + WiFi",
        sku: "EPS-TM-T88VII-UW",
        cost: 209,
        price: 329,
        stock: 0,
        units: [
          { id: "U-033", serial: "EPST880101", status: "Available", notes: "" },
          { id: "U-034", serial: "EPST880102", status: "Defective", notes: "Paper jam mechanism failure — warranty claim" },
        ],
      },
    ],
  },
  {
    id: "PRD-005",
    name: "Clover Go",
    sku: "CLV-GO",
    brand: "Clover",
    category: "Terminals",
    status: "Active",
    description: "Compact mobile card reader for Bluetooth or audio jack connection. Supports swipe, chip, and contactless.",
    tags: ["mobile", "bluetooth", "compact", "contactless", "chip"],
    variants: [
      {
        id: "VAR-005-1",
        name: "Bluetooth",
        sku: "CLV-GO-BT",
        cost: 29,
        price: 59,
        stock: 12,
        units: [],
      },
    ],
  },
  {
    id: "PRD-006",
    name: "Thermal Paper Roll 80mm",
    sku: "TPR-80MM-50PK",
    brand: "Generic",
    category: "Paper & Ribbons",
    status: "Active",
    description: "80mm x 80mm thermal receipt paper rolls, BPA-free, box of 50 rolls.",
    tags: ["thermal", "paper", "80mm", "consumable", "bpa-free"],
    variants: [
      {
        id: "VAR-006-1",
        name: "Box of 50",
        sku: "TPR-80MM-50PK-STD",
        cost: 18,
        price: 39,
        stock: 84,
        units: [],
      },
      {
        id: "VAR-006-2",
        name: "Box of 100",
        sku: "TPR-80MM-100PK-STD",
        cost: 32,
        price: 69,
        stock: 36,
        units: [],
      },
    ],
  },
  {
    id: "PRD-007",
    name: "Dejavoo Z11",
    sku: "DJV-Z11",
    brand: "Dejavoo",
    category: "Terminals",
    status: "Active",
    description: "Feature-rich countertop terminal with 3.5\" color touchscreen, WiFi, Bluetooth, EMV, NFC, and dual pricing support.",
    tags: ["countertop", "touchscreen", "dual-pricing", "nfc", "emv", "wifi"],
    variants: [
      {
        id: "VAR-007-1",
        name: "WiFi",
        sku: "DJV-Z11-WF",
        cost: 175,
        price: 279,
        stock: 0,
        units: [
          { id: "U-040", serial: "DJVZ110001", status: "Available", notes: "" },
          { id: "U-041", serial: "DJVZ110002", status: "Available", notes: "" },
          { id: "U-042", serial: "DJVZ110003", status: "Deployed",  notes: "Jerusalem Sweets — primary" },
          { id: "U-043", serial: "DJVZ110004", status: "Deployed",  notes: "Maple Leaf Market" },
          { id: "U-044", serial: "DJVZ110005", status: "Deployed",  notes: "Riverdale Hardware" },
          { id: "U-045", serial: "DJVZ110006", status: "Reserved",  notes: "Greenway Landscaping — scheduled install Jun 2026" },
        ],
      },
      {
        id: "VAR-007-2",
        name: "Ethernet",
        sku: "DJV-Z11-ETH",
        cost: 155,
        price: 249,
        stock: 0,
        units: [
          { id: "U-046", serial: "DJVZ110101", status: "Available", notes: "" },
          { id: "U-047", serial: "DJVZ110102", status: "Deployed",  notes: "Blue Ocean Diner" },
        ],
      },
    ],
  },
  {
    id: "PRD-008",
    name: "PAX A80",
    sku: "PAX-A80",
    brand: "PAX",
    category: "Terminals",
    status: "Draft",
    description: "Compact countertop smart terminal with Android OS, 4\" screen, EMV/NFC/MSR, and Ethernet/WiFi connectivity.",
    tags: ["android", "compact", "emv", "nfc", "wifi", "ethernet"],
    variants: [
      {
        id: "VAR-008-1",
        name: "Ethernet",
        sku: "PAX-A80-ETH",
        cost: 130,
        price: 209,
        stock: 0,
        units: [
          { id: "U-050", serial: "PAXA800001", status: "Available", notes: "" },
          { id: "U-051", serial: "PAXA800002", status: "Available", notes: "" },
        ],
      },
      {
        id: "VAR-008-2",
        name: "WiFi",
        sku: "PAX-A80-WF",
        cost: 145,
        price: 229,
        stock: 3,
        units: [],
      },
    ],
  },
]

const INITIAL_BRANDS = ["Clover", "PAX", "Ingenico", "Dejavoo", "Epson", "Verifone", "Square", "SwipeSimple", "Valor", "Generic"]

export default function InventoryPage() {
  return <InventoryClient initialProducts={MOCK_PRODUCTS} initialBrands={INITIAL_BRANDS} />
}
