import type { Metadata } from "next"
import { MerchantsClient } from "./MerchantsClient"
import type { Merchant } from "./MerchantsClient"

export const metadata: Metadata = { title: "Merchants" }

const MOCK_MERCHANTS: Merchant[] = [
  {
    id: "M-001",
    mid: "583920471",
    dba: "Pinnacle Sports Bar",
    legalName: "Pinnacle Hospitality Group LLC",
    processor: "Fiserv",
    status: "Active",
    ownerName: "Hector Brinn",
    ownerPhone: "(312) 555-0174",
    ownerEmail: "hector@pinnaclesportsbar.com",
    bizType: "Bar / Sports Lounge",
    mcc: "5813",
    bizPhone: "(312) 555-0175",
    website: "pinnaclesportsbar.com",
    address: "2401 N Clark St, Chicago, IL 60614",
    operatingHours: "Mon–Fri 3pm–2am, Sat–Sun 12pm–3am",
    salesRep: "Derek Foss",
    agentEmail: "derek@mtech.com",
    agentPhone: "(212) 555-0101",
    agentCode: "DF-001",
    monthlyVol: 58000,
    avgTicket: 34.0,
    riskLevel: "Medium",
    contractTerm: "3-Year",
    billingCycle: "Monthly",
    onboardedDate: "2024-02-08",
    devices: [
      { id: "D-001", brand: "Clover", type: "POS", model: "Station Duo", serial: "CLV8821034", unitId: "U-101", tidType: "TID", tid: "11029344", status: "Active", activeDate: "Feb 8, 2024", ticket: "MTECH-OB-10041", notes: "Main bar register" },
      { id: "D-002", brand: "PAX", type: "Terminal", model: "A920 Pro", serial: "PAX9910234", unitId: "U-102", tidType: "TID", tid: "11029345", status: "Active", activeDate: "Feb 8, 2024", notes: "Roaming handheld for tables" },
    ],
    docs: [
      { id: "DOC-001", docType: "Application", name: "Merchant Application Feb 2024", uploadedAt: "Feb 8, 2024", size: "2.3 MB" },
      { id: "DOC-002", docType: "Voided Check", name: "Voided Check — Feb 2024", uploadedAt: "Feb 8, 2024", size: "0.6 MB" },
    ],
    notes: [
      { id: "N-001", author: "Derek Foss", content: "Owner wants to add a second roaming device for the patio area before summer. Follow up in April.", createdAt: "Mar 14, 2026" },
    ],
    tickets: [
      { id: "MTECH-00201", subject: "Tips not applying to batch", merchant: "Pinnacle Sports Bar", merchantId: "M-001", status: "Open", priority: "High", assignedTo: "Derek Foss", createdAt: "May 4, 2026", brand: "Clover" },
    ],
    openTickets: 1,
  },
  {
    id: "M-002",
    mid: "210947382",
    dba: "Saffron Threads",
    legalName: "Saffron Threads Boutique Inc.",
    processor: "TSYS",
    status: "Active",
    ownerName: "Lena Vasquez",
    ownerPhone: "(415) 555-0293",
    ownerEmail: "lena@saffronthreads.com",
    bizType: "Clothing / Retail",
    mcc: "5621",
    bizPhone: "(415) 555-0294",
    website: "saffronthreads.com",
    address: "740 Valencia St, San Francisco, CA 94110",
    operatingHours: "Tue–Sun 10am–7pm",
    salesRep: "Amara Singh",
    agentEmail: "amara@mtech.com",
    agentPhone: "(212) 555-0202",
    agentCode: "AS-002",
    monthlyVol: 29000,
    avgTicket: 87.5,
    riskLevel: "Low",
    contractTerm: "2-Year",
    billingCycle: "Monthly",
    onboardedDate: "2023-09-15",
    devices: [
      { id: "D-011", brand: "Dejavoo", type: "Terminal", model: "Z11", serial: "DJV0041923", unitId: "U-201", tidType: "TID", tid: "22041001", status: "Active", activeDate: "Sep 15, 2023", notes: "" },
    ],
    docs: [
      { id: "DOC-011", docType: "Contract", name: "Service Agreement Sep 2023", uploadedAt: "Sep 15, 2023", size: "1.4 MB" },
      { id: "DOC-012", docType: "EIN", name: "EIN Verification", uploadedAt: "Sep 15, 2023", size: "0.3 MB" },
    ],
    notes: [
      { id: "N-011", author: "Amara Singh", content: "Merchant processes mostly high-value transactions on weekends. Prefers text messages over calls.", createdAt: "Nov 3, 2025" },
    ],
    tickets: [
      { id: "MTECH-00188", subject: "Receipt not printing after sale", merchant: "Saffron Threads", merchantId: "M-002", status: "Resolved", priority: "Low", assignedTo: "Amara Singh", createdAt: "Apr 20, 2026", brand: "Dejavoo" },
    ],
    openTickets: 0,
  },
  {
    id: "M-003",
    mid: "649201837",
    dba: "Cascadia Auto Service",
    legalName: "Cascadia Automotive LLC",
    processor: "Maverick",
    status: "Active",
    ownerName: "Owen Parrish",
    ownerPhone: "(503) 555-0381",
    ownerEmail: "owen@cascadiaauto.com",
    bizType: "Auto Repair / Service",
    mcc: "7538",
    bizPhone: "(503) 555-0382",
    website: "cascadiaauto.com",
    address: "5519 NE Sandy Blvd, Portland, OR 97213",
    operatingHours: "Mon–Sat 8am–6pm",
    salesRep: "Tomas Vega",
    agentEmail: "tomas@mtech.com",
    agentPhone: "(212) 555-0303",
    agentCode: "TV-003",
    monthlyVol: 41000,
    avgTicket: 215.0,
    riskLevel: "Low",
    contractTerm: "3-Year",
    billingCycle: "Monthly",
    onboardedDate: "2024-05-20",
    devices: [
      { id: "D-021", brand: "Verifone", type: "Terminal", model: "T650c", serial: "VFN0021834", unitId: "U-301", tidType: "TID", tid: "33021001", status: "Active", activeDate: "May 20, 2024", notes: "Front desk checkout" },
      { id: "D-022", brand: "Verifone", type: "Terminal", model: "T650c", serial: "VFN0021835", unitId: "U-302", tidType: "TID", tid: "33021002", status: "Active", activeDate: "May 20, 2024", notes: "Bay area terminal" },
    ],
    docs: [
      { id: "DOC-021", docType: "Application", name: "Onboarding Application May 2024", uploadedAt: "May 20, 2024", size: "2.1 MB" },
      { id: "DOC-022", docType: "Bank Statement", name: "Bank Statement — Apr 2024", uploadedAt: "May 20, 2024", size: "0.7 MB" },
    ],
    notes: [],
    tickets: [
      { id: "MTECH-00215", subject: "Keyed transactions getting declined", merchant: "Cascadia Auto Service", merchantId: "M-003", status: "In Progress", priority: "Medium", assignedTo: "Tomas Vega", createdAt: "May 3, 2026", brand: "Verifone" },
    ],
    openTickets: 1,
  },
  {
    id: "M-004",
    mid: "374820196",
    dba: "Ridgeline Health Clinic",
    legalName: "Ridgeline Primary Care Inc.",
    processor: "Elavon",
    status: "Active",
    ownerName: "Fatima Jalloh",
    ownerPhone: "(404) 555-0472",
    ownerEmail: "fatima@ridgelinehealth.com",
    bizType: "Medical / Healthcare",
    mcc: "8011",
    bizPhone: "(404) 555-0473",
    website: "ridgelinehealth.com",
    address: "3300 Peachtree Rd NE, Atlanta, GA 30326",
    operatingHours: "Mon–Fri 8am–5pm",
    salesRep: "Derek Foss",
    agentEmail: "derek@mtech.com",
    agentPhone: "(212) 555-0101",
    agentCode: "DF-001",
    monthlyVol: 83000,
    avgTicket: 145.0,
    riskLevel: "Low",
    contractTerm: "3-Year",
    billingCycle: "Monthly",
    onboardedDate: "2022-11-01",
    devices: [
      { id: "D-031", brand: "Ingenico", type: "Terminal", model: "Desk/3500", serial: "ING0031820", unitId: "U-401", tidType: "TID", tid: "44031001", status: "Active", activeDate: "Nov 1, 2022", notes: "Reception desk" },
      { id: "D-032", brand: "Ingenico", type: "Terminal", model: "Desk/3500", serial: "ING0031821", unitId: "U-402", tidType: "TID", tid: "44031002", status: "Active", activeDate: "Nov 1, 2022", notes: "Billing office" },
    ],
    docs: [
      { id: "DOC-031", docType: "Contract", name: "Service Agreement Nov 2022", uploadedAt: "Nov 1, 2022", size: "1.7 MB" },
      { id: "DOC-032", docType: "Photo ID", name: "Owner ID — Jalloh", uploadedAt: "Nov 1, 2022", size: "0.5 MB" },
      { id: "DOC-033", docType: "Account Update Form", name: "Address Update — Jan 2025", uploadedAt: "Jan 14, 2025", size: "0.2 MB" },
    ],
    notes: [
      { id: "N-031", author: "Derek Foss", content: "High-value monthly volume. Requires HSA/FSA card acceptance — confirmed enabled on both terminals.", createdAt: "Dec 10, 2022" },
    ],
    tickets: [],
    openTickets: 0,
  },
  {
    id: "M-005",
    mid: "918273640",
    dba: "Bluewater Seafood",
    legalName: "Bluewater Seafood Market Inc.",
    processor: "TSYS",
    status: "Inactive",
    ownerName: "Kurt Halberg",
    ownerPhone: "(617) 555-0563",
    ownerEmail: "kurt@bluewaterseafood.com",
    bizType: "Seafood Market / Retail",
    mcc: "5441",
    bizPhone: "(617) 555-0564",
    website: "",
    address: "88 Hanover St, Boston, MA 02113",
    operatingHours: "",
    salesRep: "Amara Singh",
    agentEmail: "amara@mtech.com",
    agentPhone: "(212) 555-0202",
    agentCode: "AS-002",
    monthlyVol: 17000,
    avgTicket: 52.0,
    riskLevel: "Low",
    contractTerm: "1-Year",
    billingCycle: "Monthly",
    onboardedDate: "2023-03-04",
    devices: [
      { id: "D-041", brand: "PAX", type: "Terminal", model: "A80", serial: "PAX0041923", unitId: "U-501", tidType: "TID", tid: "55041001", status: "Offline", activeDate: "Mar 4, 2023", notes: "Device offline — merchant paused operations" },
    ],
    docs: [
      { id: "DOC-041", docType: "Application", name: "Merchant Application Mar 2023", uploadedAt: "Mar 4, 2023", size: "1.9 MB" },
    ],
    notes: [
      { id: "N-041", author: "Amara Singh", content: "Owner stated business is on seasonal pause. Expects to reactivate in late August 2026.", createdAt: "Feb 12, 2026" },
    ],
    tickets: [
      { id: "MTECH-00177", subject: "Terminal showing offline after reboot", merchant: "Bluewater Seafood", merchantId: "M-005", status: "Pending Internal", priority: "High", assignedTo: "Amara Singh", createdAt: "Mar 5, 2026", brand: "PAX" },
    ],
    openTickets: 1,
  },
  {
    id: "M-006",
    mid: "462810937",
    dba: "Fieldstone Bakery",
    legalName: "Fieldstone Baking Co. LLC",
    processor: "Fiserv",
    status: "Active",
    ownerName: "Zoe Tanner",
    ownerPhone: "(514) 555-0614",
    ownerEmail: "zoe@fieldstonebakery.com",
    bizType: "Bakery / Cafe",
    mcc: "5812",
    bizPhone: "(514) 555-0615",
    website: "fieldstonebakery.com",
    address: "1102 Magazine St, New Orleans, LA 70130",
    operatingHours: "Tue–Sun 7am–4pm",
    salesRep: "Tomas Vega",
    agentEmail: "tomas@mtech.com",
    agentPhone: "(212) 555-0303",
    agentCode: "TV-003",
    monthlyVol: 22000,
    avgTicket: 16.5,
    riskLevel: "Low",
    contractTerm: "2-Year",
    billingCycle: "Monthly",
    onboardedDate: "2024-09-03",
    devices: [
      { id: "D-051", brand: "Clover", type: "POS", model: "Mini 3", serial: "CLV0051923", unitId: "U-601", tidType: "TID", tid: "66051001", status: "Active", activeDate: "Sep 3, 2024", notes: "" },
    ],
    docs: [
      { id: "DOC-051", docType: "Contract", name: "Service Agreement Sep 2024", uploadedAt: "Sep 3, 2024", size: "1.5 MB" },
      { id: "DOC-052", docType: "Voided Check", name: "Voided Check — Sep 2024", uploadedAt: "Sep 3, 2024", size: "0.4 MB" },
    ],
    notes: [],
    tickets: [],
    openTickets: 0,
  },
  {
    id: "M-007",
    mid: "701839264",
    dba: "Ironclad Fitness",
    legalName: "Ironclad Fitness & Wellness LLC",
    processor: "Maverick",
    status: "Active",
    ownerName: "Ben Ortega",
    ownerPhone: "(713) 555-0742",
    ownerEmail: "ben@ironclad.fit",
    bizType: "Gym / Fitness Studio",
    mcc: "7941",
    bizPhone: "(713) 555-0743",
    website: "ironclad.fit",
    address: "4400 Richmond Ave, Houston, TX 77027",
    operatingHours: "Mon–Fri 5am–10pm, Sat–Sun 7am–8pm",
    salesRep: "Derek Foss",
    agentEmail: "derek@mtech.com",
    agentPhone: "(212) 555-0101",
    agentCode: "DF-001",
    monthlyVol: 34000,
    avgTicket: 72.0,
    riskLevel: "Medium",
    contractTerm: "2-Year",
    billingCycle: "Quarterly",
    onboardedDate: "2024-11-18",
    devices: [
      { id: "D-061", brand: "Valor", type: "Terminal", model: "VL110", serial: "VLR0061123", unitId: "U-701", tidType: "TID", tid: "77061001", status: "Active", activeDate: "Nov 18, 2024", notes: "Front desk memberships" },
    ],
    docs: [
      { id: "DOC-061", docType: "Application", name: "Onboarding Application Nov 2024", uploadedAt: "Nov 18, 2024", size: "2.0 MB" },
      { id: "DOC-062", docType: "Bank Statement", name: "Bank Statement — Oct 2024", uploadedAt: "Nov 18, 2024", size: "0.6 MB" },
    ],
    notes: [
      { id: "N-061", author: "Derek Foss", content: "Owner wants quarterly billing to align with membership renewal cycles. High member churn in Jan and Jun.", createdAt: "Nov 19, 2024" },
    ],
    tickets: [
      { id: "MTECH-00209", subject: "Surcharge not showing on receipts", merchant: "Ironclad Fitness", merchantId: "M-007", status: "Open", priority: "Medium", assignedTo: "Derek Foss", createdAt: "Apr 28, 2026", brand: "Valor" },
    ],
    openTickets: 1,
  },
  {
    id: "M-008",
    mid: "839172046",
    dba: "Summit Print & Sign",
    legalName: "Summit Print Solutions LLC",
    processor: "TSYS",
    status: "Pending",
    ownerName: "Nadia Prokop",
    ownerPhone: "(602) 555-0873",
    ownerEmail: "nadia@summitprintsign.com",
    bizType: "Print Shop / Signage",
    mcc: "2759",
    bizPhone: "(602) 555-0874",
    website: "",
    address: "1820 W Camelback Rd, Phoenix, AZ 85015",
    operatingHours: "Mon–Fri 8am–5pm",
    salesRep: "Amara Singh",
    agentEmail: "amara@mtech.com",
    agentPhone: "(212) 555-0202",
    agentCode: "AS-002",
    monthlyVol: undefined,
    avgTicket: undefined,
    riskLevel: "Low",
    contractTerm: "2-Year",
    billingCycle: "Monthly",
    onboardedDate: "",
    devices: [],
    docs: [
      { id: "DOC-081", docType: "Application", name: "Merchant Application May 2026", uploadedAt: "May 1, 2026", size: "1.6 MB" },
    ],
    notes: [
      { id: "N-081", author: "Amara Singh", content: "Application submitted May 1. Awaiting processor approval. Follow up by May 20.", createdAt: "May 1, 2026" },
    ],
    tickets: [],
    openTickets: 0,
  },
  {
    id: "M-009",
    mid: "125839204",
    dba: "Halcyon Spa & Wellness",
    legalName: "Halcyon Wellness Group Inc.",
    processor: "Fiserv",
    status: "Closed",
    ownerName: "Rupert Ellis",
    ownerPhone: "(206) 555-0941",
    ownerEmail: "rupert@halcyonspa.com",
    bizType: "Spa / Wellness",
    mcc: "7299",
    bizPhone: "(206) 555-0942",
    website: "halcyonspa.com",
    address: "901 Pine St, Seattle, WA 98101",
    operatingHours: "Mon–Sat 10am–7pm",
    salesRep: "Tomas Vega",
    agentEmail: "tomas@mtech.com",
    agentPhone: "(212) 555-0303",
    agentCode: "TV-003",
    monthlyVol: 47000,
    avgTicket: 130.0,
    riskLevel: "Low",
    contractTerm: "3-Year",
    billingCycle: "Monthly",
    onboardedDate: "2021-07-22",
    devices: [
      { id: "D-091", brand: "Clover", type: "Terminal", model: "Flex", serial: "CLV0091234", unitId: "U-901", tidType: "TID", tid: "99091001", status: "Returned", activeDate: "Jul 22, 2021", notes: "Device returned Apr 15, 2026" },
    ],
    docs: [
      { id: "DOC-091", docType: "Contract", name: "Service Agreement Jul 2021", uploadedAt: "Jul 22, 2021", size: "1.8 MB" },
      { id: "DOC-092", docType: "Account Update Form", name: "Closure Form — Apr 2026", uploadedAt: "Apr 15, 2026", size: "0.8 MB" },
    ],
    notes: [
      { id: "N-091", author: "Tomas Vega", content: "Owner confirmed permanent closure. Equipment returned and verified. Account closed per standard process.", createdAt: "Apr 15, 2026" },
    ],
    tickets: [
      { id: "MTECH-00197", subject: "Account closure request", merchant: "Halcyon Spa & Wellness", merchantId: "M-009", status: "Closed", priority: "Low", assignedTo: "Tomas Vega", createdAt: "Apr 10, 2026" },
    ],
    openTickets: 0,
  },
]

export default function MerchantsPage() {
  return <MerchantsClient initialMerchants={MOCK_MERCHANTS} />
}
