import type { Metadata } from "next"
import { MerchantsClient } from "./MerchantsClient"
import type { Merchant } from "./MerchantsClient"

export const metadata: Metadata = { title: "Merchants" }

const MOCK_MERCHANTS: Merchant[] = [
  {
    id: "M-001",
    mid: "482910374",
    dba: "Jerusalem Sweets",
    legalName: "Jerusalem Sweets LLC",
    processor: "Fiserv",
    status: "Active",
    ownerName: "Ahmad Khalil",
    ownerPhone: "(718) 555-0142",
    ownerEmail: "ahmad@jerusalemsweets.com",
    bizType: "Restaurant / Bakery",
    mcc: "5812",
    bizPhone: "(718) 555-0143",
    website: "jerusalemsweets.com",
    address: "123 Atlantic Ave, Brooklyn, NY 11201",
    operatingHours: "Mon–Fri 8am–8pm, Sat–Sun 9am–6pm",
    salesRep: "Joan Huang",
    agentEmail: "joan@mtech.com",
    agentPhone: "(212) 555-0101",
    agentCode: "JH-001",
    monthlyVol: 45000,
    avgTicket: 28.5,
    riskLevel: "Low",
    contractTerm: "3-Year",
    billingCycle: "Monthly",
    onboardedDate: "2024-03-15",
    devices: [
      { id: "D-001", brand: "Clover", type: "POS", model: "Station Duo", serial: "C4T2891023", unitId: "U-101", tidType: "TID", tid: "10029302", status: "Active", activeDate: "Mar 15, 2024", ticket: "MTECH-OB-10012", notes: "Primary POS at register 1" },
    ],
    docs: [
      { id: "DOC-001", docType: "Application", name: "Merchant Application 2024", uploadedAt: "Mar 15, 2024", size: "2.1 MB" },
      { id: "DOC-002", docType: "Voided Check", name: "Voided Check — Mar 2024", uploadedAt: "Mar 15, 2024", size: "0.8 MB" },
    ],
    notes: [
      { id: "N-001", author: "Joan Huang", content: "Merchant is very responsive. Interested in adding loyalty program integration.", createdAt: "Apr 10, 2026" },
    ],
    tickets: [
      { id: "MTECH-00102", subject: "Terminal freezing during peak hours", merchant: "Jerusalem Sweets", merchantId: "M-001", status: "Open", priority: "High", assignedTo: "Joan Huang", createdAt: "May 5, 2026", brand: "Clover" },
    ],
    openTickets: 1,
  },
  {
    id: "M-002",
    mid: "619438201",
    dba: "Green Valley Market",
    legalName: "Green Valley Market Inc.",
    processor: "TSYS",
    status: "Active",
    ownerName: "Sandra Park",
    ownerPhone: "(347) 555-0288",
    ownerEmail: "sandra@greenvalleymarket.com",
    bizType: "Grocery / Retail",
    mcc: "5411",
    bizPhone: "(347) 555-0289",
    website: "greenvalleymarket.com",
    address: "450 Flatbush Ave, Brooklyn, NY 11225",
    operatingHours: "Daily 7am–10pm",
    salesRep: "Moe Kadi",
    agentEmail: "moe@mtech.com",
    agentPhone: "(212) 555-0202",
    agentCode: "MK-002",
    monthlyVol: 78000,
    avgTicket: 42.0,
    riskLevel: "Low",
    contractTerm: "2-Year",
    billingCycle: "Monthly",
    onboardedDate: "2023-11-08",
    devices: [
      { id: "D-011", brand: "PAX", type: "Terminal", model: "A920 Pro", serial: "P8823910234", unitId: "U-201", tidType: "TID", tid: "20049011", status: "Active", activeDate: "Nov 8, 2023", notes: "" },
      { id: "D-012", brand: "Epson", type: "Printer", model: "TM-T88VII", serial: "EP00182937", unitId: "U-202", printerConn: "Ethernet (LAN)", printerIp: "192.168.1.50", status: "Active", activeDate: "Nov 8, 2023", notes: "Receipt printer at checkout" },
    ],
    docs: [
      { id: "DOC-011", docType: "Contract", name: "Service Agreement 2023", uploadedAt: "Nov 8, 2023", size: "1.4 MB" },
      { id: "DOC-012", docType: "EIN", name: "EIN Verification", uploadedAt: "Nov 8, 2023", size: "0.3 MB" },
    ],
    notes: [
      { id: "N-011", author: "Moe Kadi", content: "Owner prefers contact via email only. Expansion to second location planned for Q3 2026.", createdAt: "Mar 22, 2026" },
    ],
    tickets: [
      { id: "MTECH-00089", subject: "Printer not connecting to network", merchant: "Green Valley Market", merchantId: "M-002", status: "Resolved", priority: "Medium", assignedTo: "Moe Kadi", createdAt: "Apr 18, 2026", brand: "Other" },
    ],
    openTickets: 0,
  },
  {
    id: "M-003",
    mid: "305827491",
    dba: "Sunrise Coffee Co.",
    legalName: "Sunrise Coffee Co. LLC",
    processor: "Maverick",
    status: "Active",
    ownerName: "Elise Fontaine",
    ownerPhone: "(646) 555-0374",
    ownerEmail: "elise@sunrisecoffee.com",
    bizType: "Coffee Shop / Cafe",
    mcc: "5812",
    bizPhone: "(646) 555-0375",
    website: "sunrisecoffeeco.com",
    address: "88 West 72nd St, New York, NY 10023",
    operatingHours: "Mon–Fri 6am–7pm, Sat–Sun 7am–5pm",
    salesRep: "Joan Huang",
    agentEmail: "joan@mtech.com",
    agentPhone: "(212) 555-0101",
    agentCode: "JH-001",
    monthlyVol: 32000,
    avgTicket: 11.5,
    riskLevel: "Low",
    contractTerm: "3-Year",
    billingCycle: "Monthly",
    onboardedDate: "2024-01-22",
    devices: [
      { id: "D-021", brand: "Clover", type: "Terminal", model: "Flex", serial: "CF3901234", unitId: "U-301", tidType: "TID", tid: "30012001", status: "Active", activeDate: "Jan 22, 2024", notes: "Handheld device for tableside orders" },
    ],
    docs: [
      { id: "DOC-021", docType: "Application", name: "Onboarding Application Jan 2024", uploadedAt: "Jan 22, 2024", size: "1.8 MB" },
      { id: "DOC-022", docType: "Bank Statement", name: "Bank Statement — Dec 2023", uploadedAt: "Jan 22, 2024", size: "0.5 MB" },
    ],
    notes: [],
    tickets: [
      { id: "MTECH-00095", subject: "Clover Flex won't charge", merchant: "Sunrise Coffee Co.", merchantId: "M-003", status: "In Progress", priority: "Medium", assignedTo: "Joan Huang", createdAt: "May 2, 2026", brand: "Clover" },
    ],
    openTickets: 1,
  },
  {
    id: "M-004",
    mid: "741928305",
    dba: "Harbor View Sushi",
    legalName: "Harbor View Restaurant Group LLC",
    processor: "Fiserv",
    status: "Active",
    ownerName: "Kenji Nakamura",
    ownerPhone: "(212) 555-0491",
    ownerEmail: "kenji@harborviewsushi.com",
    bizType: "Restaurant / Sushi Bar",
    mcc: "5812",
    bizPhone: "(212) 555-0492",
    website: "harborviewsushi.com",
    address: "12 Fulton St, New York, NY 10038",
    operatingHours: "Tue–Sun 12pm–10pm",
    salesRep: "Zu Jia He Cen",
    agentEmail: "zu@mtech.com",
    agentPhone: "(212) 555-0303",
    agentCode: "ZC-003",
    monthlyVol: 95000,
    avgTicket: 68.0,
    riskLevel: "Medium",
    contractTerm: "3-Year",
    billingCycle: "Monthly",
    onboardedDate: "2023-08-14",
    devices: [
      { id: "D-031", brand: "Dejavoo", type: "POS", model: "Z11", serial: "DJ0091823", unitId: "U-401", tidType: "TID", tid: "40091003", status: "Active", activeDate: "Aug 14, 2023", notes: "" },
      { id: "D-032", brand: "Dejavoo", type: "Terminal", model: "Z8", serial: "DJ0091824", unitId: "U-402", tidType: "TID", tid: "40091004", status: "Active", activeDate: "Aug 14, 2023", notes: "Bar terminal" },
    ],
    docs: [
      { id: "DOC-031", docType: "Contract", name: "Service Agreement 2023", uploadedAt: "Aug 14, 2023", size: "1.6 MB" },
      { id: "DOC-032", docType: "Photo ID", name: "Owner ID — Nakamura", uploadedAt: "Aug 14, 2023", size: "0.7 MB" },
    ],
    notes: [
      { id: "N-031", author: "Zu Jia He Cen", content: "High-volume merchant. Requires priority response for ticket submissions. Bar area has separate terminal.", createdAt: "Sep 5, 2023" },
    ],
    tickets: [],
    openTickets: 0,
  },
  {
    id: "M-005",
    mid: "198374650",
    dba: "Maple Leaf Market",
    legalName: "Maple Leaf Grocery Inc.",
    processor: "TSYS",
    status: "Inactive",
    ownerName: "David Tremblay",
    ownerPhone: "(718) 555-0519",
    ownerEmail: "david@mapleleafmarket.ca",
    bizType: "Grocery / Convenience",
    mcc: "5411",
    bizPhone: "(718) 555-0520",
    website: "",
    address: "709 Kings Highway, Brooklyn, NY 11223",
    operatingHours: "",
    salesRep: "Joan Huang",
    agentEmail: "joan@mtech.com",
    agentPhone: "(212) 555-0101",
    agentCode: "JH-001",
    monthlyVol: 21000,
    avgTicket: 18.0,
    riskLevel: "Low",
    contractTerm: "1-Year",
    billingCycle: "Monthly",
    onboardedDate: "2022-06-01",
    devices: [
      { id: "D-041", brand: "Ingenico", type: "Terminal", model: "Move/5000", serial: "ING0041923", unitId: "U-501", tidType: "TID", tid: "50041001", status: "Offline", activeDate: "Jun 1, 2022", notes: "Device offline — owner not responding" },
    ],
    docs: [
      { id: "DOC-041", docType: "Application", name: "Merchant Application 2022", uploadedAt: "Jun 1, 2022", size: "1.9 MB" },
    ],
    notes: [
      { id: "N-041", author: "Joan Huang", content: "Account marked inactive — owner has not renewed contract. Follow up scheduled for June 2026.", createdAt: "Jan 15, 2026" },
    ],
    tickets: [
      { id: "MTECH-00073", subject: "Terminal offline — unable to process", merchant: "Maple Leaf Market", merchantId: "M-005", status: "Pending Internal", priority: "High", assignedTo: "Joan Huang", createdAt: "Mar 10, 2026", brand: "Ingenico" },
    ],
    openTickets: 1,
  },
  {
    id: "M-006",
    mid: "867310294",
    dba: "Brooklyn Bistro LLC",
    legalName: "Brooklyn Bistro LLC",
    processor: "Elavon",
    status: "Active",
    ownerName: "Maria Esposito",
    ownerPhone: "(718) 555-0638",
    ownerEmail: "maria@brooklynbistro.com",
    bizType: "Restaurant / Italian",
    mcc: "5812",
    bizPhone: "(718) 555-0639",
    website: "brooklynbistro.com",
    address: "220 Court St, Brooklyn, NY 11201",
    operatingHours: "Mon–Sun 11am–11pm",
    salesRep: "Moe Kadi",
    agentEmail: "moe@mtech.com",
    agentPhone: "(212) 555-0202",
    agentCode: "MK-002",
    monthlyVol: 62000,
    avgTicket: 55.0,
    riskLevel: "Low",
    contractTerm: "3-Year",
    billingCycle: "Monthly",
    onboardedDate: "2023-04-10",
    devices: [
      { id: "D-051", brand: "PAX", type: "POS", model: "Aries8", serial: "PA8901234", unitId: "U-601", tidType: "TID", tid: "60021001", status: "Active", activeDate: "Apr 10, 2023", notes: "" },
      { id: "D-052", brand: "PAX", type: "Terminal", model: "A80", serial: "PA8901235", unitId: "U-602", tidType: "TID", tid: "60021002", status: "Active", activeDate: "Apr 10, 2023", notes: "Outdoor patio terminal" },
    ],
    docs: [
      { id: "DOC-051", docType: "Contract", name: "Service Contract 2023", uploadedAt: "Apr 10, 2023", size: "2.0 MB" },
      { id: "DOC-052", docType: "Voided Check", name: "Voided Check — Apr 2023", uploadedAt: "Apr 10, 2023", size: "0.4 MB" },
    ],
    notes: [],
    tickets: [],
    openTickets: 0,
  },
  {
    id: "M-007",
    mid: "523491087",
    dba: "Atlas Auto Parts",
    legalName: "Atlas Auto Parts & Supply Corp.",
    processor: "Maverick",
    status: "Active",
    ownerName: "George Petrakis",
    ownerPhone: "(718) 555-0712",
    ownerEmail: "george@atlasautoparts.com",
    bizType: "Auto Parts / Retail",
    mcc: "5533",
    bizPhone: "(718) 555-0713",
    website: "atlasautoparts.com",
    address: "1845 Utica Ave, Brooklyn, NY 11234",
    operatingHours: "Mon–Sat 8am–6pm",
    salesRep: "Moe Kadi",
    agentEmail: "moe@mtech.com",
    agentPhone: "(212) 555-0202",
    agentCode: "MK-002",
    monthlyVol: 38000,
    avgTicket: 92.0,
    riskLevel: "Medium",
    contractTerm: "2-Year",
    billingCycle: "Quarterly",
    onboardedDate: "2024-07-01",
    devices: [
      { id: "D-061", brand: "Verifone", type: "Terminal", model: "T650c", serial: "VF0011938", unitId: "U-701", tidType: "TID", tid: "70011001", status: "Active", activeDate: "Jul 1, 2024", notes: "" },
    ],
    docs: [
      { id: "DOC-061", docType: "Application", name: "Onboarding Application Jul 2024", uploadedAt: "Jul 1, 2024", size: "2.3 MB" },
      { id: "DOC-062", docType: "FNS", name: "FNS Authorization Letter", uploadedAt: "Jul 1, 2024", size: "0.6 MB" },
    ],
    notes: [
      { id: "N-061", author: "Moe Kadi", content: "Owner requested quarterly billing due to seasonal revenue fluctuations in winter months.", createdAt: "Jul 2, 2024" },
    ],
    tickets: [
      { id: "MTECH-00098", subject: "Batch not settling automatically", merchant: "Atlas Auto Parts", merchantId: "M-007", status: "Open", priority: "Medium", assignedTo: "Moe Kadi", createdAt: "Apr 30, 2026", brand: "Verifone" },
    ],
    openTickets: 1,
  },
  {
    id: "M-008",
    mid: "902837461",
    dba: "Upper West Cafe",
    legalName: "Upper West Hospitality LLC",
    processor: "TSYS",
    status: "Pending",
    ownerName: "Chris Abboud",
    ownerPhone: "(646) 555-0884",
    ownerEmail: "chris@upperwestcafe.com",
    bizType: "Coffee Shop / Cafe",
    mcc: "5812",
    bizPhone: "(646) 555-0885",
    website: "",
    address: "310 West 86th St, New York, NY 10024",
    operatingHours: "Mon–Fri 7am–6pm, Sat 8am–4pm",
    salesRep: "Zu Jia He Cen",
    agentEmail: "zu@mtech.com",
    agentPhone: "(212) 555-0303",
    agentCode: "ZC-003",
    monthlyVol: undefined,
    avgTicket: undefined,
    riskLevel: "Low",
    contractTerm: "3-Year",
    billingCycle: "Monthly",
    onboardedDate: "",
    devices: [],
    docs: [
      { id: "DOC-081", docType: "Application", name: "Merchant Application Apr 2026", uploadedAt: "Apr 28, 2026", size: "1.7 MB" },
    ],
    notes: [
      { id: "N-081", author: "Zu Jia He Cen", content: "Application submitted. Awaiting bank approval. Follow up by May 15.", createdAt: "Apr 28, 2026" },
    ],
    tickets: [],
    openTickets: 0,
  },
  {
    id: "M-009",
    mid: "374918205",
    dba: "Crown Jewelers Inc.",
    legalName: "Crown Jewelers International Inc.",
    processor: "Fiserv",
    status: "Closed",
    ownerName: "Farida Al-Rashid",
    ownerPhone: "(212) 555-0941",
    ownerEmail: "farida@crownjewelers.com",
    bizType: "Jewelry / Retail",
    mcc: "5944",
    bizPhone: "(212) 555-0942",
    website: "crownjewelers.com",
    address: "580 5th Ave, New York, NY 10036",
    operatingHours: "Mon–Sat 10am–7pm",
    salesRep: "Joan Huang",
    agentEmail: "joan@mtech.com",
    agentPhone: "(212) 555-0101",
    agentCode: "JH-001",
    monthlyVol: 120000,
    avgTicket: 485.0,
    riskLevel: "High",
    contractTerm: "3-Year",
    billingCycle: "Annual",
    onboardedDate: "2021-02-10",
    devices: [
      { id: "D-091", brand: "Ingenico", type: "Terminal", model: "Desk/3500", serial: "ING0091023", unitId: "U-901", tidType: "TID", tid: "90011001", status: "Returned", activeDate: "Feb 10, 2021", notes: "Device returned on account closure" },
    ],
    docs: [
      { id: "DOC-091", docType: "Contract", name: "Service Agreement 2021", uploadedAt: "Feb 10, 2021", size: "1.5 MB" },
      { id: "DOC-092", docType: "Account Update Form", name: "Closure Form — Apr 2026", uploadedAt: "Apr 20, 2026", size: "0.9 MB" },
    ],
    notes: [
      { id: "N-091", author: "Joan Huang", content: "Account closed per owner request. Merchant relocated internationally. All equipment returned and confirmed.", createdAt: "Apr 20, 2026" },
    ],
    tickets: [
      { id: "MTECH-00091", subject: "Account closure — MTECH-00091", merchant: "Crown Jewelers Inc.", merchantId: "M-009", status: "Closed", priority: "Low", assignedTo: "Joan Huang", createdAt: "Apr 15, 2026" },
    ],
    openTickets: 0,
  },
]

export default function MerchantsPage() {
  return <MerchantsClient initialMerchants={MOCK_MERCHANTS} />
}
